apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-svc
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - name: nginx
      port: 80
      targetPort: 80
    - name: multitool
      port: 8080
      targetPort: 8080
