apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Новый фильм</title>
    </head>
    <body>
      <h1>Форсаж 10 в кино!</h1>
    </body>
    </html>
