apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: {{ .Values.metadata.namespace }}
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Тестовая страница</title>
    </head>
    <body>
      <h1>K8S-NETOLOGY</h1>
    </body>
    </html>
