apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-svc
  labels:
    app: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - name: {{ .Values.name }}
      port: 9001
      targetPort: 80
