apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html-v2
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Зверополис 2</title>
    </head>
    <body>
      <h1>Любимые персонажи возвращаются !!</h1>
    </body>
    </html>
